### PR TITLE
Fixes in mapping.xml

### PR DESCRIPTION
**Pull request by rolfkleef**
It is present for .../recipient-region-budget/...

### CODE REVIEW

**Comment by andylolz** [comment]
Same goes for:

```
/iati-organisation/recipient-org-budget/budget-line/value/@currency
```

Applies to v2.02 for both, too.  Applies to v2.01 for `recipient-org-budget`.

**Review by samuele-mattiuzzo — APPROVED** [review]

**Comment by andylolz** [comment]
This updates the mapping for `BudgetIdentifier`. This mapping should be removed as per #138.

**Comment by rolfkleef** [comment]
hi Andy, we're looking into and discussing in the Validator implementation project, as there are some implementation difficulties:

- The BudgetIdentifier codelist is a non-embedded codelist, as is the related BudgetIdentifierVocabulary codelist. So these lists are not bound to a specific IATI version.
- Since vocabulary code "1" is withdrawn, it in fact is withdrawn for all IATI versions, not just for IATI version 2.03 (that could only work for an embedded codelist).
- The codelist mapping file is tied to IATI versions, so indeed we could remove the mapping from v2.03, and basically stop validating the codes for v2.03.
- We're following this path in an implementation-specific way in the Validator right now: we've removed the BudgetIdentifier codelist for version 2.03 and so there won't be feedback on codes.
- I would currently argue that the mapping.xml for each version should be the same across versions **for non-embedded codelists**. There _may_ be differences for **embedded codelists**.

Linking this comment to #138 as well.

**Comment by andylolz** [comment]
Hi @rolfkleef,

I agree with the first three points.

>  * The codelist mapping file is tied to IATI versions, so indeed we could remove the mapping from v2.03, and basically stop validating the codes for v2.03.

Exactly. That’s what #139 does.

>  * I would currently argue that the mapping.xml for each version should be the same across versions for non-embedded codelists. There may be differences for embedded codelists.

I’ve spent some time thinking about this, and I’m struggling to see the argument for it. Why should mappings be the same across versions for non-embedded codelists?

Just to expand a bit: Although the mapping file lives in this repo, it can be thought of as more closely related to the schema than to the codelists (in fact [elsewhere, it has been suggested](https://github.com/IATI/IATI-Schemas/issues/430) that this mapping could live inside the schema). The schema can change to use or cease to use codelists between different versions. This is independent of the type of codelist.

**Pull request merged**
