### PR TITLE
Output v1.0x codelists as CLv3 (v1.05)

### PR DESCRIPTION
**Pull request by andylolz**
Refs #153.

The v2tov3.py file [comes from here](https://github.com/IATI/IATI-Codelists/blob/version-2.03/v2tov3.py), so actually there’s very little new code in this PR.

### CODE REVIEW

**Comment by andylolz** [comment]
@referencebot build

**Comment by andylolz** [comment]
Okay great, so the demo above includes CLv2 codelists [like this one](http://153-clv3-v1.05-iati-codelists-refbot.surge.sh/codelists/downloads/clv2/xml/ActivityStatus.xml), but also CLv3 codelists [like this one](http://153-clv3-v1.05-iati-codelists-refbot.surge.sh/codelists/downloads/clv3/xml/ActivityStatus.xml).

There are no links to these codelists e.g. on [the ActivityStatus codelist page](http://153-clv3-v1.05-iati-codelists-refbot.surge.sh/codelists/ActivityStatus/), because the template for the codelist page also needs to be changed. This is done in IATI/IATI-Standard-SSOT#298.

**Comment by andylolz** [comment]
Added one more commit, which fixes #152.

**Comment by andylolz** [comment]
Okay – brought this PR up-to-date.

I’ve attempted to update @referencebot, too, so I’ll test it out here.

@referencebot build.

**Comment by andylolz** [comment]
Okay – brought this PR up-to-date.

I’ve attempted to update @referencebot, too, so I’ll test it out here.

@referencebot build.

**Comment by andylolz** [comment]
Cool – seems like this PR && referencebot are both now python3 friendly.

**Review by samuele-mattiuzzo — APPROVED** [review]

**Comment by andylolz** [comment]
Great – thanks for merging!

**Pull request merged**
