### PR TITLE
Python 3 Upgrade 1.04

### PR DESCRIPTION
**Pull request by sargentfrancesca**

### CODE REVIEW

**Review by Ocre42 — APPROVED** [review]

**Comment by andylolz** [comment]
Looks like this adds all of the IATI-Codelists-NonEmbedded code, rather than adding it as a submodule. So that doesn’t look right to me.

Regardless, adding IATI-Codelists-NonEmbedded as a submodule probably isn’t part of the python3 upgrade, right? So I’m not sure that it should be part of this PR.

**Comment by sargentfrancesca** [comment]
Hi @andylolz 

Previously, the IATI-Codelists-NonEmbedded were cloned as part of the `gen` script, and I switched to a submodule for consistencies stake. I can see, though, that we need to 'choose one method', as it's confusing that we would initialise and update the NonEmbedded repository, but then clone it if it doesn't exist in the `gen` script. I'll have a look at this, thanks for flagging.

Included within the Python3 work is some sysadmin work - in the way that we are upgrading our servers to support the more recent versions of Python 3.x, which has lent to a cleanup of how the SSOT is deployed, as currently it isn't robust. This isn't reflected directly in the code (although, we have added amended IATI-Websites/deploy already), so I can understand that it doesn't seem to make sense to be included. However, it does, given our opportune cleanup within this particular work sprint.

Hope that makes sense!

**Comment by sargentfrancesca** [comment]
@andylolz 

Addressing your comment https://github.com/IATI/IATI-Codelists/pull/219#issuecomment-493989286 here, as we are following up on different threads.

That's a completely valid point, and a good perspective - amending the inclusion method of the Codelists is a seemingly innocent change that could affect users negatively. I'm going to think about this some more.

**Comment by andylolz** [comment]
> Addressing your comment #219 (comment) here, as we are following up on different threads.

Apologies, yes! I was trying to comment before they were merged, but it happened very rapidly!

> That's a completely valid point, and a good perspective - amending the inclusion method of the Codelists is seemingly innocent change that could affect users. I'm going to think about this some more.

Sorry yeah – that’s the only reason I mentioned the “how you divide up PRs” bit. This includes a potentially breaking change for external tools reliant on the SSOT. But someone could easily miss it, because it’s packaged up as a python3 upgrade (which is largely an internal issue that third parties probably don’t need to concern themselves with.)

**Comment by sargentfrancesca** [comment]
@andylolz I get it, totally. Glad you flagged.

>It includes a potentially breaking change for external tools reliant on the SSOT. But someone could easily miss it...

New plan - i'll going to remove the `.gitmodules` script from each respective branch and preserve what already exists. I'm still going to consider submodule vs subtree in the future, though this isn't a priority.

**Comment by andylolz** [comment]
> I get it, totally. Glad you flagged.

Ace – much appreciated.

> New plan - i'll going to remove the .gitmodules script from each respective branch and preserve what already exists

Okay but… It’s worth again noting that some of these PRs (i.e. this one; #219) include **all the code**, whereas others (#217; #218; #220) just include the .gitmodules file. I think the latter is correct and the former is not. That’s what I was getting at here:

> this adds all of the IATI-Codelists-NonEmbedded code, rather than adding it as a submodule. So that doesn’t look right to me

---

> I'm still going to consider submodule vs subtree in the future, though this isn't a priority.

Kk cool, fair enough. I added a bit of explanation [over here](https://github.com/IATI/IATI-Codelists/pull/219#issuecomment-493989286) as to why I don’t think a submodule is appropriate here. But I don’t feel terribly strongly about it, and it’s your call! But if there’s a chance it’ll break third party systems, please do let us know before making the change.

**Comment by sargentfrancesca** [comment]
@andylolz as you've probably noticed, the submodules have been removed - business should resume as usual!

**Comment by andylolz** [comment]
Many thanks for acting so swiftly on this, @sargentfrancesca! Much appreciated.

**Comment by andylolz** [comment]
> the submodules have been removed - business should resume as usual!

~~Looks like there’s still a trace of it on `version-2.03`… I guess a `git rm --cached IATI-Codelists-NonEmbedded` will sort it?~~ Sorted now! Thanks

**Pull request merged**
