### PR TITLE
Fix duplicate crs-add typo

### PR DESCRIPTION
**Pull request by Bjwebb**

### CODE REVIEW

**Comment by andylolz** [comment]
👍

**Comment by andylolz** [comment]
I just tried using `pyiati.validator`, and it’s breaking for me _I think_ due to this issue /cc @hayfield.

**Comment by dalepotter** [comment]
@andylolz Would be interesting to look into this further, since I'm not sure this is an intended behaviour of pyIATI. Feel free to open an issue in the IATI/pyIATI repo with the full details...

Otherwise @Bjwebb - we'll add this to Monday maintenance projects - sorry it's been sitting here for so long...

**Comment by andylolz** [comment]
> Feel free to open an issue in the IATI/pyIATI repo with the full details...

Cool – I’ve opened IATI/pyIATI#224.

**Review by hayfield — APPROVED** [review]
:+1:

**Comment by hayfield** [comment]
This is a change to fix an XPath so that it matches something that could reasonably be correct.

Am merging at this point so that it can be updated in pyIATI. This will not be reflected on the website until the website is next generated (though what will be shown on the website is debatable since it is generally assumed (even stated in the [IATI-Codelists README](https://github.com/IATI/IATI-Codelists#codelist-mapping)) that only attributes (rather than element text) should be validated against Codelists).

**Comment by andylolz** [comment]
> This will not be reflected on the website until the website is next generated (though what will be shown on the website is debatable since it is generally assumed (even stated in the [IATI-Codelists README](https://github.com/IATI/IATI-Codelists#codelist-mapping)) that only attributes (rather than element text) should be validated against Codelists).

It looks like the website doesn’t break, but also doesn’t get this quite right i.e. I’d expect [the CRS channel code codelist page](http://iatistandard.org/202/codelists/CRSChannelCode/) to say something like:

> ## Use this codelist for
>  * [//iati-activity/crs-add/channel-code/text()](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/crs-add/channel-code/)

**Comment by hayfield** [comment]
The SSOT has yet to be updated with this change.

https://github.com/IATI/IATI-Standard-SSOT/pull/122 updates the SSOT.

**Comment by andylolz** [comment]
> The SSOT has yet to be updated with this change.

Sorry yeah – I realised that after I posted, but I also tested it locally (including this PR) and the same comment applies.

I sent a PR to fix it: IATI/IATI-Standard-SSOT#123

**Pull request merged**
