### PR TITLE
[Changes not required] Moving DocumentCategory and GazetteerAgency to Non-Core [v2.03]

### PR DESCRIPTION
**Pull request by Ocre42**
These codelists are no longer part of the Core, moved to Non-Core 
To be merged alongside: https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/299

### CODE REVIEW

**Comment by andylolz** [comment]
> These codelists are no longer part of the Core, moved to Non-Core

Sorry, I don’t understand… When was this change agreed?

Please could you provide a link to the relevant proposal? Thanks

**Comment by PetyaKangalova** [comment]
Hi @andylolz . During the 2.03 upgrade process there was an agreement for a number of codelists to be moved from embedded to non-embedded. See [Final technical proposal post](https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097) and non-embedded codelist tab in [the summary table.](https://docs.google.com/spreadsheets/d/1XWnzesMvLebIVLk47OIXATfhcjESVcaGnw8SJpOuCCk/edit#gid=1565466021).

This error has only now been spotted that following 2.03 launch the title for `Document Category` and `Gazeteer Agency` were not changed, so we are fixing it now.

I will be adding this to Discuss before deploying the changes and will aim to do so tomorrow morning at the latest.

**Comment by andylolz** [comment]
Thanks for this explanation, @petyakangalova.

However, I didn't *think* this was an error. I thought the final proposal explicitly excluded these two codelists. See this post from Hayden, who was part of the technical team at the time:
https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/12

**Comment by stevieflow** [comment]
> thought the final proposal explicitly excluded these two codelists. 

Yes, I had understood that too.

**Comment by PetyaKangalova** [comment]
Hi @stevieflow  and @andylolz - you are both correct. It is not a 2.03 error but an error on my side, so apologies for creating the confusion!

I have now updated the [google sheet ](https://docs.google.com/spreadsheets/d/1XWnzesMvLebIVLk47OIXATfhcjESVcaGnw8SJpOuCCk/edit#gid=1565466021) to reflect the final agreement for the two codelists during the 2.03 upgrade process and have changed the title of this pull request to **Not-required**.

The two codelist were kept as core because of the format change from version 1 to version 2 of the IATI standard.  With the current [codelist management process](http://reference.iatistandard.org/203/codelists-guides/codelist-management/) the two codelist should stay as **core** , meaning that any additions or modifications can only happen at a major upgrade.

**Comment by stevieflow** [comment]
Thanks @PetyaKangalova 

Only on Friday was I looking at the DocumentCategory codelist and how to change, [on this thread on Discuss](https://discuss.iatistandard.org/t/iati-coverage-timing-and-scope-of-next-update/1141/34)

Alas, it looks like we are bounded by decisions that were made during the implementation of 2.03

**Comment by andylolz** [comment]
Thanks for resolving this quickly, @PetyaKangalova. I admit I panicked a bit when I spotted these 6 pull requests, because this is a breaking change, but it wasn’t clear from the pull requests what the schedule was for merging and deploying. I’m pleased to learn that the plan was to add a discuss post before deploying the changes. But it occurs to me that I don’t know what the agreed process is for SSOT-related bugfixes, and I wasn’t able to find any documentation about it on the reference site.

It would be good if some process could be publicly documented for exactly this sort of scenario. Recently, some [minor copy fixes](https://github.com/IATI/IATI-Schemas/pull/436) were made to the schema, but without any notification. It would be handy to have a documented process for bugfixes, in order to manage expectations.

Also, I notice [the process for making changes to non-embedded codelists](http://reference.iatistandard.org/203/codelists-guides/codelist-management/#non-embedded-codelists-non-core) has recently changed on the reference site. [Previously, it provided a lot of detail](https://github.com/IATI/IATI-Extra-Documentation/blob/2420a814/en/codelists/codelist-management.rst#updates-to-non-embedded-codelists), including that there would be a 7 day notification period. It now says changes can be made “at any point in time, subject to applicable notification and/or consultation”. Maybe this is a very minor point, but I think there’s value in ensuring these processes are documented clearly for the benefit of all parties.

**Comment by andylolz** [comment]
> the two codelist should stay as core , meaning that any additions or modifications can only happen at a major upgrade.

^^ I guess this was just a typo. I think it’s true that additions or modifications to embedded (core) codelists can happen at minor upgrades, too.

**Pull request closed without merging**
