### PR TITLE
Remove reference to the BudgetIdentifier codelist in the definition of country-budget-items/budget-item/@code (v2.03 upgrade)

### LINKED ISSUE #138: Remove reference to the BudgetIdentifier codelist in the definition of country-budget-items/budget-item/@code
The [IATI TAG Standards Day notes](https://docs.google.com/spreadsheets/d/1RRE5IjyirIp-JFRF94JUNL6IEKnEU42uGzlWoj1yJ0A/edit#gid=0) (row 103) says:

> *Proposal*: Remove reference to the `BudgetIdentifier` codelist in the definition of `country-budget-items/budget-item/@code`
>
> *Outcome*: **Accept**
>
> *Discussion*: We would deprecate at 2.03 and remove in integer, although it was noted that there is no process on the deprecation of individual elements. Comms would need to be provided to publishers about this, perhaps as separate guidelines.

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #138.

This relates to IATI/IATI-Codelists-NonEmbedded#242.

This also updates the README to replace an old BudgetIdentifier example.

### CODE REVIEW

**Comment by andylolz** [comment]
Bumping this, since it’s part of the v2.03 upgrade.

**Comment by andylolz** [comment]
7 months on, it doesn’t look like this will be reviewed or merged. Closing.

**Comment by andylolz** [comment]
I don’t remember why I closed this, but it still appears to be valid so reopening.

**Comment by PetyaKangalova** [comment]
Testing @referencebot.

**Comment by PetyaKangalova** [comment]
Hi @referencebot, please build a site with the suggested changes.

**Comment by andylolz** [comment]
So if you compare the [generated budget-item page](http://138-remove-ref-to-budgetidentifier-code-1-iati-codelists-refbot.surge.sh/activity-standard/iati-activities/iati-activity/country-budget-items/budget-item/#attributes) with the [v2.03 budget-item page](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/country-budget-items/budget-item/#attributes), you’ll see that the following line has been removed:

> This value must be on the _[BudgetIdentifier codelist](http://reference.iatistandard.org/203/codelists/BudgetIdentifier/)_, if the relevant vocabulary is used.

That’s what this PR does, fixing #138.

**Comment by andylolz** [comment]
Similarly, the reference page for [`iati-activity/country-budget-items/budget-item`](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/country-budget-items/budget-item/#attributes) currently says:
> This value must be on the [BudgetIdentifier codelist](http://reference.iatistandard.org/203/codelists/BudgetIdentifier/), if the relevant vocabulary is used.

For v2.03 of the standard, this advice is not correct.

This line is not present for [the same page in the version generated from this pull request](http://138-remove-ref-to-budgetidentifier-code-1-iati-codelists-refbot.surge.sh/activity-standard/iati-activities/iati-activity/country-budget-items/budget-item/#attributes).

**Comment by andylolz** [comment]
Doesn’t look like this will be merged; closing.

**Comment by akmiller01** [comment]
Hi @andylolz , taking a look at mapping.xml today and I would like to merge this Pull Request, but it appears like the original branch with the corrections was deleted. Please let me know if you'd like to recreate the branch and make another PR.

**Comment by andylolz** [comment]
That’s great – thanks for this, @akmiller01.

I’ve just created a replacement PR: #266.

**Pull request closed without merging**
