### PR TITLE
Allow elements in codelist to have custom namespace

### PR DESCRIPTION
**Pull request by allthatilk**
Add ability to have custom namespaces in codelists.

Add ability to add namespace attributes too.

### CODE REVIEW

**Comment by andylolz** [comment]
> Awaiting confirmation about how this relates to attributes.

I guess you also need to add a bunch of these:

```xml
<xs:anyAttribute processContents="lax" namespace="##other"/>
```

…as per #160.

**Comment by allthatilk** [comment]
@andylolz already on it, was awaiting confirmation from BAs that we wanted this and then had to go to a meeting haha

**Comment by andylolz** [comment]
Yeah I’m just making the point that this duplicates work I did in a PR 2 months ago. If you’d reviewed (even today) and said “do this for other elements too” I could have done it and saved you guys time, that’s all.

**Comment by allthatilk** [comment]
@andylolz no worries. Sometimes PRs just get lost in the pile =/ Thanks anyway.

**Comment by andylolz** [comment]
> Sometimes PRs just get lost in the pile

That’s understandable.

I guess one way to avoid this would be to always create an issue first, which acts as something like a declaration of intention to do a particular piece of work. Then if someone spots that the work has already been done, or that they’ve already started that work, or even if they’re just excited to know that work is on the cards, they can flag it.

**Review by Ocre42 — APPROVED** [review]

**Pull request merged**
