### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by HerbCaudill**

### CODE REVIEW

**Comment by amy-silcock** [comment]
Proposed new wording for the Indicator Measure Codelist:

To specify how an indicator is being measured. This includes qualitative and quantitative values.

**Comment by samuele-mattiuzzo** [comment]
> Proposed new wording for the Indicator Measure Codelist:

does this mean this issue still needs working on? just merge directly what HerbCaudill has done? @amy-silcock 

fwiw: there's a few conflicts lying around so I won't merge this branch. Once Amy's comment has been clarified, I'll re-do the work from scratch.

**Comment by amy-silcock** [comment]
Thanks @samuele-mattiuzzo the only change needed is to the `<description><narrative>` text. It should now read: `To specify how an indicator is being measured. This includes qualitative and quantitative values.`

**Comment by samuele-mattiuzzo** [comment]
Code is obsolete and we can't merge this:

- the `IndicatorMeasure` codelist now lives in [IATI-Codelists-NonEmbedded](https://github.com/IATI/IATI-Codelists-NonEmbedded/)
- the change for `FR` not relevant

Closing and taking care of it in the correct [place](https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/296)

**Pull request closed without merging**
